services:
  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - microservices

  user-service:
    build: 
      context: ./microservices/user_service
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - microservices
  
  inventory-service:
    build: 
      context: ./microservices/inventory_service
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - microservices

networks:
  microservices:
    name: microservices